- Debug/index.html
- index.html
- scripts/scripts.js
- styles/styles.css
> #121: Added colors to math buttons palette

- styles/styles.css
> #119: Dynamically shift the editor section down as the history grow

- Debug/index.html
- index.html
- styles/styles.css
> 121: Seperated math palette buttons in groups

- Debug/index.html
- index.html
note: clear all is  a placeholder for now
> #122: Add text and icon labels

- index.html
- scripts/scripts.js
- styles/styles.css
> #156: Changed background image to sheet of paper

- index.html
- scripts/scripts.js
- styles/styles.css
> #118 added row edition (single mode only, no automation/cleanups)

- scripts/scripts.js
- styles/styles.css
> #154: defined crossout lines CSS style -> blue

- index.html
- styles/styles.css
> Pulled undo button right, aligned with add step button

- index.html
- scripts/scripts.js
- styles/styles.css
Fixed Microsoft Edge layout display issues: 
- tooltips,
- visible editor on the main page
- 4-bytes colors
> #231: Fixed Microsoft Edge layout display issues

- src/components/Editor/components/MySteps/components/MyStepsList/components/Step/index.js
- src/components/Editor/components/MySteps/components/MyStepsList/components/Step/styles.css
- src/components/Editor/components/MySteps/components/MyStepsList/index.js
- src/components/Editor/components/MyWork/components/MyWorkEditorButtons/components/MyWorkFooter/index.js
- src/components/Editor/components/MyWork/components/MyWorkEditorButtons/index.js
- src/components/Editor/components/MyWork/index.js
- src/components/Editor/index.js
- src/components/Editor/styles.css
- src/components/Home/index.js
- src/components/index.js
- src/index.html
*fixed notbeook background
*when size height exceeds it scrolls properly now
*added scrollbards when annotation or equation is step is too wide
*restored alt+enter shortcut to add step
*shift+backspace undoes last action
*added success dialog when saving page
*edit and delete buttons should be inline on edge now
*annotation is being cleared after clear all
*undo button isn't visible at the beginning
> #329 & #190: Minor ui fixes

- src/components/Editor/index.js
- src/components/Home/index.js
- src/components/LandingPage/index.js
- src/components/NotFound/index.js
- src/components/Partners/index.js
- src/components/Privacy/index.js
- src/components/SignIn/index.js
- src/components/UserDetails/index.js
- src/components/index.js
- src/styles/styles.scss
Reverts benetech/MathShare#853
> Revert "Feature/#831 fix landmark issues in audit"

- src/redux/problem/reducer.js
This PR will fix https://github.com/benetech/MathShare/issues/1057
> #1057 - fix stale problem glitch

- src/components/index.js
- src/redux/userProfile/actions.js
- src/redux/userProfile/reducer.js
- src/redux/userProfile/sagas.js
Reference - https://github.com/benetech/MathShare/issues/1061
> show intercom button only to teachers

- src/components/UserDetails/styles.scss
Ref - https://github.com/benetech/MathShare/issues/1079
> fix firefox UI

- src/components/HeaderDropdown/index.js
- src/components/HeaderDropdown/styles.scss
Ref - https://github.com/benetech/MathShare/issues/1084
> add space between dropdown options

- src/components/Home/index.js
- src/components/PageIndex/index.js
Ref - https://github.com/benetech/MathShare/issues/1091
> #1091 - remove twitter link

- src/components/Home/index.js
- src/components/PageIndex/index.js
Ref - https://github.com/benetech/MathShare/issues/1091
> Fix build issue

- src/components/Home/index.js
Ref - https://github.com/benetech/MathShare/pull/1097/files
> #1091 - remove unnecessary React.Fragment

- src/components/index.js
- src/redux/userProfile/sagas.js
Ref - https://github.com/benetech/MathShare/issues/1092
> #1092 - skip math palette customization

- src/components/palettes.json
Ref - https://github.com/benetech/MathShare/issues/1029
> #1029 - remove text button from json

- src/index.js
- src/redux/modal/sagas.js
- src/redux/router/reducer.js
- src/redux/router/sagas.js
- src/services/events.js
- src/services/misc.js
Ref - https://github.com/benetech/MathShare/issues/742
> Focus Optimization

- src/services/misc.js
Reverts benetech/MathShare#1117
> Revert "Commenting blur to debug an issue on QA"

- src/components/PageIndex/index.js
- src/components/PageIndex/styles.scss
Fixes https://github.com/benetech/MathShare/issues/1101.  @rupeshparab Let me know if the styling is affected by using divs instead of ol/li.
> #1101 - Remove single-item list mark-up for create problem set button

- package-lock.json
- package.json
- src/components/Editor/components/MyWork/components/MyWorkEditorArea/components/SpeechToTextButton/index.js
- src/components/Editor/index.js
- src/components/HeaderDropdown/index.js
- src/components/Home/components/NewProblemsForm/index.js
- src/components/Home/index.js
- src/components/LandingPage/index.js
- src/components/ModalContainer/components/ShareModal/index.js
- src/components/PageIndex/index.js
- src/components/index.js
- src/redux/userProfile/sagas.js
Reverts benetech/MathShare#1119
> Revert "remove intercom to debug blur"

- src/components/Editor/components/MySteps/components/MyStepsList/index.js
- src/components/Editor/components/MyWork/components/MyWorkEditorArea/components/SpeechToTextButton/index.js
- src/components/Editor/components/ProblemHeader/index.js
- src/components/index.js
Reverts benetech/MathShare#1121
> Revert "remove hotkeys to debug blur"

- src/components/Home/index.js
- src/redux/problem/sagas.js
- src/redux/problemList/actions.js
- src/redux/problemList/reducer.js
- src/redux/problemList/sagas.js
- src/redux/router/sagas.js
- src/services/misc.js
Ref - https://github.com/benetech/MathShare/issues/742
> #742 - avoid unnecesary reloads and improve focus performance

- src/components/index.js
- src/redux/problem/actions.js
- src/redux/problem/sagas.js
Ref - https://github.com/benetech/MathShare/issues/1026
> #1026 - integrate api change to capture finished

- src/components/ModalContainer/components/SignInModal/index.js
- src/components/ModalContainer/components/SignInModal/styles.scss
- src/components/ModalContainer/index.js
- src/components/SignIn/core.js
- src/components/SignIn/index.js
- src/components/SignIn/styles.scss
- src/redux/problemList/sagas.js
- src/strings.js
Ref - https://github.com/benetech/MathShare/issues/973
> #973 - prompt students to signin

- src/components/Editor/components/ProblemHeader/index.js
- src/components/Editor/components/ProblemHeader/styles.scss
- src/components/Editor/index.js
Ref - https://github.com/benetech/MathShare/issues/1031
> #1031 - add common nav bar to problem page

- src/components/Home/components/Navigation/Problem/index.js
- src/components/Home/components/NewProblemsForm/index.js
- src/strings.js
Ref - https://github.com/benetech/MathShare/issues/762
> #762 - update screen reader text for view sketch button

- src/components/PageIndex/index.js
- src/components/PageIndex/styles.scss
- src/redux/userProfile/apis.js
- src/redux/userProfile/sagas.js
- src/strings.js
Ref - https://github.com/benetech/MathShare/issues/977
> Changes on Dashboard

- src/components/PageIndex/index.js
- src/components/PageIndex/styles.scss
- src/redux/problemList/sagas.js
Ref - https://github.com/benetech/MathShare/issues/844
> #844 - fix archived sets

- src/components/Home/index.js
> #1151 - fix dropdown issue

- src/components/Home/index.js
- src/components/index.js
- src/redux/userProfile/reducer.js
Ref - https://github.com/benetech/MathShare/issues/1092
> #1092 - fix for new problem set in new tab

- src/strings.js
Ref - https://github.com/benetech/MathShare/issues/976
> capitalize benefits text

- src/strings.js
Ref - https://github.com/benetech/MathShare/issues/1170
> #1170 - update copyright year

- src/components/Home/index.js
Reverts benetech/MathShare#1160
> Revert "add logs"

- src/components/Editor/components/ProblemHeader/index.js
- src/components/Editor/index.js
Ref - https://github.com/benetech/MathShare/pull/1128
> address feedback of PR 1128

- src/components/PageIndex/index.js
- src/components/PageIndex/styles.scss
Ref - https://github.com/benetech/MathShare/issues/844
> move archived sets link

- src/components/Home/components/Navigation/Problems/index.js
- src/redux/problem/sagas.js
- src/redux/problemList/sagas.js
> fix bugs related to problem set steps and changing order

- src/redux/userProfile/reducer.js
- src/redux/userProfile/sagas.js
Ref - https://github.com/benetech/MathShare/issues/1199
> #1199 - fix saga throttle issue

- src/components/Editor/components/MyWork/components/MathPalette/components/MathButtonsGroup/components/MathButtonsRow/components/MathButton/index.js
Ref - https://github.com/benetech/MathShare/issues/1190
> #1190 - fix mathlive shortcuts

- src/components/PageIndex/index.js
fix linter issue of https://github.com/benetech/MathShare/pull/1189
> fix linter issue

- src/components/Editor/components/MyWork/components/MathPalette/components/MathButtonsGroup/components/MathButtonsRow/components/MathButton/index.js
Ref - https://github.com/benetech/MathShare/issues/1203
> #1203 - fix automatic calculation

- src/components/Editor/components/ProblemHeader/index.js
- src/components/ModalContainer/index.js
- src/components/index.js
Ref - https://github.com/benetech/MathShare/issues/1204
> #1204 - integrate api changes for go back link

- src/components/Home/components/Navigation/Problem/index.js
- src/components/Home/components/Navigation/Problem/styles.scss
- src/redux/problem/reducer.js
- src/redux/problemList/actions.js
- src/redux/problemList/reducer.js
Ref - https://github.com/benetech/MathShare/issues/1202
> #1202 - fix problem creator edit bug

- src/components/Editor/components/MyWork/index.js
- src/redux/problem/reducer.js
- src/redux/problemList/reducer.js
Ref - https://github.com/benetech/MathShare/issues/1234
> #1234 - fix scratchpad js

- src/components/Home/styles.scss
Ref - https://github.com/benetech/MathShare/issues/1237
> #1237 - css fixes

- src/components/ModalContainer/components/ConfirmationModal/index.js
- src/components/ModalContainer/components/ConfirmationModal/styles.scss
- src/components/ModalContainer/components/NewProblemSetShareModal/index.js
- src/components/ModalContainer/components/NewProblemSetShareModal/styles.scss
- src/components/ModalContainer/components/ProblemModal/index.js
- src/components/ModalContainer/components/ProblemModal/styles.scss
- src/components/ModalContainer/components/SaveModal/index.js
- src/components/ModalContainer/components/SaveModal/styles.scss
- src/components/ModalContainer/components/ShareModal/index.js
- src/components/ModalContainer/components/ShareModal/styles.scss
- src/components/ModalContainer/components/SignInModal/index.js
- src/components/ModalContainer/components/TitleEditModal/index.js
- src/components/ModalContainer/components/TitleEditModal/styles.scss
Ref - https://github.com/benetech/MathShare/issues/1224
> fix modal accessibility

- src/components/Editor/components/MyWork/index.js
Ref - https://github.com/benetech/MathShare/issues/1094
> #1094 - shift+enter shortcut

- src/components/PageIndex/index.js
Ref - https://github.com/benetech/MathShare/issues/1250
> #1250 - benefits of signing in

- src/components/Editor/components/MyWork/components/MyWorkEditorButtons/components/InputContainerSelectors/index.js
- src/components/Editor/components/MyWork/components/MyWorkEditorButtons/components/InputContainerSelectors/styles.scss
Ref - https://github.com/benetech/MathShare/issues/1251
> #1251 - css fixes

- src/components/index.js
- src/config.js
Ref - https://github.com/benetech/MathShare/issues/1255
> #1255 - add protocol to url

- src/redux/tts/sagas.js
Ref - https://github.com/benetech/MathShare/issues/997
> #997 - fix tts url when content changes

- src/components/Editor/components/MyWork/index.js
- src/components/Editor/components/MyWork/styles.scss
Ref - https://github.com/benetech/MathShare/issues/1269
> #1269 - css fix

- src/components/Editor/components/MySteps/components/MyStepsList/components/Step/index.js
- src/components/Editor/components/MySteps/components/MyStepsList/components/Step/styles.scss
- src/components/Editor/components/MySteps/components/MyStepsList/index.js
- src/redux/router/sagas.js
- src/redux/tts/reducer.js
- src/redux/tts/sagas.js
Ref:
https://github.com/benetech/MathShare/issues/995
https://github.com/benetech/MathShare/issues/1268
> Issue with crossouts and steps

- src/components/Editor/components/MyWork/styles.scss
Ref - https://github.com/benetech/MathShare/issues/1269
> #1269 - fix css for firefox

- src/components/Editor/components/MySteps/components/MyStepsList/components/Step/index.js
- src/components/Editor/components/MyWork/components/MyWorkEditorArea/index.js
- src/components/Editor/components/MyWork/index.js
- src/components/Editor/components/ProblemHeader/index.js
- src/components/Home/components/Navigation/Problem/index.js
- src/components/Home/components/NewProblemsForm/index.js
- src/services/speech.js
PR - https://github.com/benetech/MathShare/issues/1268
> Reading Crossouts

- src/components/Editor/index.js
- src/redux/problem/sagas.js
Ref - https://github.com/benetech/MathShare/issues/1272
> #1272 - fix issues with auto step addition

- src/components/Editor/components/MyWork/components/MathPalette/index.js
- src/components/Editor/components/MyWork/index.js
- src/components/palettes.json
Ref - https://github.com/benetech/MathShare/issues/1147
> #1147 - calc shortcut update and add support multiple key combinations

- src/services/speech.js
Ref - https://github.com/benetech/MathShare/issues/1279
https://github.com/benetech/MathShare/issues/1282
> #1279 - change rules

- src/components/Home/components/ButtonsPaletteChooser/index.js
- src/components/Home/components/Navigation/Problem/index.js
- src/components/Home/components/NewProblemsForm/index.js
- src/components/ModalContainer/components/CommonModal/index.js
- src/components/ModalContainer/components/ConfirmationModal/index.js
- src/components/ModalContainer/components/PersonalizationModal/index.js
- src/components/ModalContainer/components/PersonalizationModal/styles.scss
- src/components/ModalContainer/components/ProblemSetShareModal/index.js
- src/components/ModalContainer/components/TitleEditModal/index.js
- src/components/ModalContainer/index.js
- src/components/index.js
- src/redux/modal/sagas.js
Ref - https://github.com/benetech/MathShare/issues/1266
>  Common Modal Component

- src/redux/userProfile/sagas.js
> #1206 - change role key

- src/components/palettes.json
- src/services/speech.js
Ref - https://github.com/benetech/MathShare/issues/1282
> #1282 - fix crossout and replace

- src/components/Editor/components/MyWork/components/MathPalette/components/MathButtonsGroup/components/MathButtonsRow/components/MathButton/index.js
- src/components/Editor/components/MyWork/components/MathPalette/index.js
- src/components/palettes.json
Ref - https://github.com/benetech/MathShare/issues/1147
> #1147 - fix tooltip

- src/components/ModalContainer/components/PersonalizationModal/index.js
Ref - https://github.com/benetech/MathShare/issues/1006
> #1006 - fix aria label id

- src/redux/userProfile/sagas.js
> #1206 - experimental change to check if intercom has booted

- src/redux/userProfile/actions.js
- src/redux/userProfile/sagas.js
- src/services/intercom.js
> #1206 - add wait for intercom boot

- src/components/PageIndex/index.js
> #1206 - remove incorrect event

- src/components/Home/components/Footer/styles.scss
- src/components/Home/components/Header/styles.scss
- src/components/Home/components/SocialFooter/styles.scss
Ref - https://github.com/benetech/MathShare/issues/846
> #846 - update colors

- src/components/index.js
- src/redux/userProfile/sagas.js
> #1206 - integrate intercom custom attributes

- src/components/index.js
- src/redux/userProfile/sagas.js
- src/services/mathshare.js
> #1206 -  move parameters from user details event to custom attributes

- src/components/ModalContainer/components/PersonalizationModal/index.js
- src/components/ModalContainer/components/PersonalizationModal/styles.scss
Ref - https://github.com/benetech/MathShare/issues/1006
> #1006 - add % character

- src/components/index.js
- src/services/events.js
Ref - https://github.com/benetech/MathShare/issues/1310
> #1310 - more options activation and dismissal

- src/components/index.js
> #1206 - fix array in attribute

- src/redux/problem/sagas.js
Ref - https://github.com/benetech/MathShare/issues/1284
> #1284 - skip save when not needed

- src/components/Home/components/CopyLink/index.js
- src/components/Home/components/CopyLink/styles.scss
Ref - https://github.com/benetech/MathShare/issues/1241
> #1241 - fix focus issues on copy link

- src/components/Editor/components/MyWork/components/MyWorkEditorButtons/components/MyWorkFooter/index.js
Ref
https://github.com/benetech/MathShare/issues/1304
https://github.com/benetech/MathShare/issues/1305
> #1304 - fix undo handling

- src/components/Home/index.js
- src/components/PageIndex/index.js
- src/redux/problemList/actions.js
- src/redux/problemList/apis.js
- src/redux/problemList/sagas.js
- src/strings.js
Ref - https://github.com/benetech/MathShare/issues/1227
> Archive solution sets

- src/components/PageIndex/styles.scss
Ref - https://github.com/benetech/MathShare/issues/1227
> #1227 - fix css

- src/components/Editor/index.js
- src/redux/problem/sagas.js
Ref - https://github.com/benetech/MathShare/issues/1284
> #1284 - fix cases where explanation is empty and cancel edit cases

- src/components/Editor/components/MyWork/index.js
Ref - https://github.com/benetech/MathShare/issues/1335
> #1335 - fix tts for my work

- src/components/ModalContainer/components/PersonalizationModal/index.js
Ref - https://github.com/benetech/MathShare/issues/1330
> #1330 - remove debounce and add validations to speed input box

- src/components/Home/index.js
- src/components/ModalContainer/components/ProblemSetShareModal/index.js
Ref - https://github.com/benetech/MathShare/issues/1259
> #1259 - add common event

- src/components/Home/index.js
- src/components/ModalContainer/components/ProblemSetShareModal/index.js
Ref - https://github.com/benetech/MathShare/issues/1259
> #1259 - rename event

- src/redux/router/sagas.js
- src/redux/sagas.js
- src/redux/ui/reducer.js
- src/redux/ui/sagas.js
- src/redux/ui/selectors.js
- src/strings.js
Ref - https://github.com/benetech/MathShare/issues/1310
> #1310 - announce dropdown collapsed

- src/components/Editor/components/MyWork/components/MyWorkEditorButtons/components/MyWorkFooter/index.js
Ref - https://github.com/benetech/MathShare/issues/1356
> #1356 - remove delete button from my work

- src/components/Button/index.js
- src/components/DynamicSVG/index.js
- src/components/Editor/components/MyWork/components/MathPalette/components/MathButtonsGroup/components/MathButtonsRow/components/MathButton/index.js
Ref - https://github.com/benetech/MathShare/issues/1293
> Fix tooltips

- src/components/Home/index.js
- src/components/ModalContainer/components/ProblemSetShareModal/index.js
Ref - https://github.com/benetech/MathShare/issues/1259
> move assign-a-set-link event to copy link button

- src/components/Home/components/CopyLink/index.js
- src/components/Home/components/CopyLink/styles.scss
- src/components/ModalContainer/components/ProblemSetShareModal/styles.scss
Ref - https://github.com/benetech/MathShare/issues/1241
> #1241 - increase modal width and add js for auto height expansion

- src/components/Home/components/CopyLink/index.js
Ref - https://github.com/benetech/MathShare/issues/1241
> #1241 - fix copy link ids

- src/components/Editor/components/MyWork/components/MyWorkEditorButtons/components/MyWorkFooter/index.js
Reverts benetech/MathShare#1357
> Revert "#1356 - remove delete button from my work"

- src/components/Editor/components/MySteps/components/MyStepsList/components/Step/index.js
- src/styles/styles.scss
Ref - https://github.com/benetech/MathShare/issues/1262
> #1262 - use readonly mathlive editor to allow text selection

- src/services/review.js
Ref - https://github.com/benetech/MathShare/issues/1284
> #1284 - fix last step in progress case

- v2/src/pages/Dashboard/index.js
- v2/src/pages/Home/styles.scss
https://github.com/benetech/MathShare/issues/1402
> add login prompt

- v2/src/components/Card/index.js
- v2/src/components/Card/styles.scss
- v2/src/components/ProblemCard/index.js
- v2/src/components/ProblemCard/styles.scss
https://github.com/benetech/MathShare/issues/1414
> fix color on basis of id

- v2/src/components/SignIn/styles.scss
- v2/src/pages/Header/styles.scss
https://github.com/benetech/MathShare/issues/1398
> #1398 - add few responsiveness fixes

- v2/src/pages/Problem/index.js
- v2/src/pages/Problem/styles.scss
https://github.com/benetech/MathShare/issues/1424
> #1424 - add ellipsis in affixed equation

- v2/src/pages/Dashboard/index.js
- v2/src/pages/Problem/styles.scss
- v2/src/pages/ProblemSet/styles.scss
- v2/src/pages/index.js
https://github.com/benetech/MathShare/issues/1412
> #1412 - reduce font size

- v2/src/pages/Header/index.js
- v2/src/pages/Header/styles.scss
https://github.com/benetech/MathShare/issues/1395
> #1395 - add redirect to dashboard

- v2/src/components/Step/index.js
- v2/src/components/Step/styles.scss
- v2/src/pages/Problem/index.js
- v2/src/pages/Problem/styles.scss
- v2/src/redux/problem/actions.js
- v2/src/redux/problem/reducer.js
- v2/src/redux/problem/sagas.js
- v2/src/services/review.js
- v2/src/strings.js
Ref - https://github.com/benetech/MathShare/issues/1440
> #1440 - integrate save api

- v2/src/components/ProblemCard/styles.scss
- v2/src/pages/ProblemSet/styles.scss
- v2/src/pages/styles.scss
https://github.com/benetech/MathShare/issues/1413
https://github.com/benetech/MathShare/issues/1408
https://github.com/benetech/MathShare/issues/1415
> Frontend V2

- v2/src/components/Step/index.js
- v2/src/pages/Problem/index.js
- v2/src/pages/Problem/styles.scss
- v2/src/pages/styles.scss
- v2/src/redux/problem/actions.js
- v2/src/redux/problem/reducer.js
https://github.com/benetech/MathShare/issues/1441
> #1441 - remove popup and move add step when keyboard is opened

- v2/src/components/Card/index.js
- v2/src/pages/ProblemSet/index.js
https://github.com/benetech/MathShare/issues/1479
> #1479 - change popover to modal for keyboard accessibility

- v2/src/pages/Problem/index.js
- v2/src/pages/Problem/styles.scss
https://github.com/benetech/MathShare/issues/1420
https://github.com/benetech/MathShare/issues/1423
> #1420 #1423 - fix background and change affix position

- v2/src/components/Step/index.js
https://github.com/benetech/MathShare/issues/1530
> #1530 - improve scroll

- v2/src/index.html
https://github.com/benetech/MathShare/issues/1532
> #1532 - fix double scrollbar

- src/components/UserDetails/index.js
- v2/src/pages/UserDetails/index.js
https://github.com/benetech/MathShare/issues/1521
https://github.com/benetech/MathShare/issues/1522
> #1521 #1522 - persist form data on steps

- v2/src/pages/ProblemSet/index.js
https://github.com/benetech/MathShare/issues/1531
> #1531 - fix rendering for view links

- v2/src/pages/Dashboard/index.js
- v2/src/pages/Dashboard/styles.scss
- v2/src/redux/problemSetList/apis.js
- v2/src/redux/problemSetList/reducer.js
- v2/src/redux/problemSetList/sagas.js
- v2/src/redux/problemSetList/selectors.js
- v2/src/redux/userProfile/actions.js
- v2/src/redux/userProfile/sagas.js
https://github.com/benetech/MathShare/issues/1483
> #1483 - integrate pagination api and add load more button

- v2/src/pages/ProblemSet/styles.scss
https://github.com/benetech/MathShare/issues/1422
> #1422 - fix title overflow

- v2/src/components/Card/index.js
- v2/src/components/Card/styles.scss
- v2/src/components/ProblemCard/styles.scss
- v2/src/components/Sidebar/index.js
- v2/src/components/Sidebar/styles.scss
- v2/src/pages/Dashboard/index.js
- v2/src/pages/Home/styles.scss
- v2/src/pages/styles.scss
- v2/src/strings.js
Ref:
https://github.com/benetech/MathShare/issues/1454
https://github.com/benetech/MathShare/issues/1459
https://github.com/benetech/MathShare/issues/1460
https://github.com/benetech/MathShare/issues/1463
> Tablet css changes

- v2/src/pages/Header/index.js
- v2/src/strings.js
https://github.com/benetech/MathShare/issues/1551
> #1551 - add accessible label to signout dropdown

- v2/src/pages/Problem/styles.scss
Ref: https://github.com/benetech/MathShare/issues/1422
> #1422 - fix spacing on title

- v2/package-lock.json
- v2/package.json
- v2/src/pages/Problem/index.js
- v2/src/pages/Problem/styles.scss
- v2/src/pages/index.js
- v2/src/redux/ui/actions.js
- v2/src/redux/ui/reducer.js
Ref - https://github.com/benetech/MathShare/issues/1557
> #1557 - handle location of add step button for mobile devices

- v2/src/pages/index.js
Ref - https://github.com/benetech/MathShare/issues/1556
> #1556 - fix re-rendering of view

- v2/src/components/ProblemCard/index.js
- v2/src/pages/Problem/index.js
- v2/src/pages/Problem/styles.scss
- v2/src/pages/index.js
- v2/src/redux/ui/actions.js
- v2/src/redux/ui/reducer.js
Ref: https://github.com/benetech/MathShare/issues/1557
> #1557 - experimental fix for mobile devices

- v2/src/components/Step/styles.scss
- v2/src/pages/Problem/index.js
- v2/src/pages/Problem/styles.scss
Ref - https://github.com/benetech/MathShare/issues/1557
> #1557 - handle keyboard for iOS

- v2/src/components/Step/styles.scss
- v2/src/pages/Problem/index.js
Ref - https://github.com/benetech/MathShare/issues/1558
> #1558 - selection bars using css

- v2/src/pages/Header/index.js
Ref - https://github.com/benetech/MathShare/issues/1551
> #1551 - add aria expanded for profile

- v2/src/pages/Header/index.js
Ref - https://github.com/benetech/MathShare/issues/1564
> #1564 - add presentation role to name in dropdown

- v2/src/pages/Problem/index.js
- v2/src/pages/Problem/styles.scss
- v2/src/redux/problemSetList/reducer.js
- v2/src/redux/router/reducer.js
- v2/src/redux/router/sagas.js
Ref:
https://github.com/benetech/MathShare/issues/1565
https://github.com/benetech/MathShare/issues/1566
https://github.com/benetech/MathShare/issues/1567
> Finish Feature

- v2/src/components/ProblemCard/index.js
- v2/src/pages/Problem/index.js
Ref - https://github.com/benetech/MathShare/issues/1566
> #1566 - use svg title in place of aria-label

- v2/src/redux/router/sagas.js
https://github.com/benetech/MathShare/issues/1587
> #1587 - fix progress update bug

- src/components/Editor/components/MyWork/index.js
https://github.com/benetech/MathShare/issues/1586
> #1586 - fix painterro integration

- v2/src/components/Card/index.js
- v2/src/components/Modals/ProblemSetShareModal/index.js
- v2/src/pages/Dashboard/index.js
https://github.com/benetech/MathShare/issues/1569
https://github.com/benetech/MathShare/issues/1568
> Share Modal

- package-lock.json
- package.json
https://github.com/benetech/MathShare/issues/1622
> #1622 - upgrade watson package

- src/components/Home/components/NewProblemsForm/styles.scss
- src/components/index.js
- src/strings.js
https://github.com/benetech/MathShare/issues/1620
> #1620 - add title length validation

- src/components/PageIndex/styles.scss
https://github.com/benetech/MathShare/issues/1585
> #1585 - change load more button color

- v2/src/pages/ProblemSet/index.js
https://github.com/benetech/MathShare/issues/1599
> #1599 - fix backspace and shift+enter

- v2/src/pages/ProblemSet/index.js
- v2/src/pages/ProblemSet/styles.scss
- v2/src/pages/index.js
https://github.com/benetech/MathShare/issues/1603
> #1603 - move problem space for larger screens

- v2/src/pages/Dashboard/styles.scss
Ref - https://github.com/benetech/MathShare/issues/1594
> #1594 - new set button size

- v2/src/components/Step/index.js
- v2/src/components/Step/styles.scss
Ref - https://github.com/benetech/MathShare/issues/1605
> #1605 - word wrap on prompt

- v2/src/pages/ProblemSet/index.js
https://github.com/benetech/MathShare/issues/1600
> #1600 - fix higlight issue

- src/redux/userProfile/sagas.js
- v2/src/redux/problemSetList/sagas.js
Ref - https://github.com/benetech/MathShare/issues/1585
> #1585 - integrate load more

- v2/src/components/Modals/ProblemSetShareModal/index.js
- v2/src/pages/ProblemSet/index.js
Ref:
https://github.com/benetech/MathShare/issues/1608
https://github.com/benetech/MathShare/issues/1609
> #1608 #1609 - add assign set button and modal

- v2/src/components/Modals/ProblemSetShareModal/index.js
- v2/src/strings.js
https://github.com/benetech/MathShare/issues/1609
> #1609 - update modal title

- automation/yarn.lock
- package-lock.json
- package.json
- v2/package-lock.json
- v2/package.json
https://github.com/benetech/MathShare/issues/1651
> #1651 - update non-breaking packages

- v2/src/components/Sidebar/index.js
https://github.com/benetech/MathShare/issues/1628
> #1628 - user title

- v2/src/components/Sidebar/index.js
https://github.com/benetech/MathShare/issues/1632
> #1632 - remove unused icons

- v2/src/pages/ProblemSet/index.js
https://github.com/benetech/MathShare/issues/1599
> #1599 - fix issue with deleting complete title

- v2/src/pages/ProblemSet/index.js
- v2/src/strings.js
https://github.com/benetech/MathShare/issues/1601
> #1601 - disable add new button

- v2/src/components/Sidebar/index.js
- v2/src/pages/Dashboard/index.js
- v2/src/redux/ui/actions.js
- v2/src/redux/ui/sagas.js
- v2/src/strings.js
https://github.com/benetech/MathShare/issues/1636
> #1636 - add scroll to section

- v2/src/components/Sidebar/index.js
- v2/src/redux/problemSetList/sagas.js
- v2/src/redux/ui/sagas.js
https://github.com/benetech/MathShare/issues/1637
> #1637 - scroll only after all data has been loaded

- v2/src/components/Sidebar/index.js
- v2/src/components/Sidebar/styles.scss
- v2/src/pages/styles.scss
Ref - https://github.com/benetech/MathShare/issues/1639
> #1639 - activate links based on scroll position

- src/components/Editor/components/MySteps/components/MyStepsList/components/Step/styles.scss
- src/components/Editor/components/ProblemHeader/styles.scss
- src/components/Home/components/NewProblemsForm/index.js
https://github.com/benetech/MathShare/issues/1620
> #1620 - 2000 limit and overflow

- src/components/Editor/components/MyWork/index.js
- src/components/Editor/index.js
- src/components/Editor/stepsOperations.js
- src/redux/problem/reducer.js
Ref - https://github.com/benetech/MathShare/issues/1634
> #1634 - fix painterro usage
